version: '3'
services:
  jenkins:
    image: jenkinsci/blueocean
    container_name: jenkins
    user: root
    networks:
      - ci
    ports:
      - 8888:8080
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - sonarqube
  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    networks:
      - ci
    ports:
      - 9000:9000
    links:
      - db
    environment:
        SONARQUBE_JDBC_USERNAME: sonar
        SONARQUBE_JDBC_PASSWORD: sonar
        SONARQUBE_JDBC_URL: jdbc:postgresql://db:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_plugins:/opt/sonarqube/extensions/plugins
  db:
    image: postgres
    container_name: sonarqube_db
    networks:
      - ci
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    networks:
      - ci
    ports:
      - 8122:8081
      - 8123:8123
    volumes:
      - nexus-data:/nexus-data
  mysql:
    image: mysql:5.7
    container_name: cd_db
    networks:
      - ci
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  jenkins_data:
  postgres_data:
  sonarqube_conf:
  sonarqube_plugins:
  nexus-data:
  mysql_data:

networks:
  ci:
    driver: bridge