version: '3'
services:
  app:
    build: .
    container_name: app
    ports:
      - 8083:8080
    links:
      - mysql
  mysql:
    image: mysql:5.7.26
    container_name: db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - mysql_data:/var/lib/mysql 
  adminer:
    image: adminer
    container_name: db_client
    ports:
      - 3307:8080
    links:
      - mysql:db
volumes:
  mysql_data: